### ISSUE TITLE
Create tutorial to teach people how to use rings.

### ISSUE THREAD

**Issue by Callmore** [Indev450/SRB2Kart-NURINGS#9]
Quoted from [sunflower on discord](https://discord.com/channels/1055805287946268722/1064148263143481404/1180638387741397052):

> I probably want go with the cecho idea (Example: https://streamable.com/psaqpz). Have something similar as this pop up each session until you've used rings once, and mute it until the person rejoin. I am aware you can store it but I think 1 time each session (or more if you don't end up using rings) is fine enough because if someone end up using rings by mistake which can happen from time to time after using an item they do not permanently lose access to the tip.

https://github.com/Indev450/SRB2Kart-NURINGS/assets/22885888/d946210a-7ea7-4a1c-a459-fee1fb549c97
*video reuploaded here for convinence*

Maybe some sort of popup that shows up after holding 10+ rings for more than 30 seconds, telling the player to hold their ring use button to use rings. After that it would be up to the player to experiment with using rings with other boosts to stack and extend them.

Also some sort of popup when a player maxes out the amount of rings they can use at once, explaining that they have hit the limit and that it will reset shortly.

**Comment by Indev450** [comment]
So, is 280fc3d57b29ebce38e31e69c3360bb6e72c85cd enough for now?
